# Generated by Django 4.1 on 2022-09-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
